server.port=8888
spring.kafka.bootstrap-servers=kafka1:19092
spring.kafka.single-topic-name=ktopic
spring.kafka.group-id=11
logging.level.root=WARN
logging.level.com.exploration=DEBUG
logging.file.name=logs/app.log
