name: ci.yml

on: [push, workflow_dispatch] # workflow_dispatch is github manual trigger

jobs:
  ci:
    environment: dev # this and other github environments are configured in Settings > Environments
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v7

    - name: setup env
      run: |
        sudo apt-get update

        echo "available java versions"
        update-alternatives --display java
        echo "$ java -version"
        java -version
        echo "$ javac -version"
        javac -version

        sudo apt-get install -y openjdk-18-jdk-headless
        export JAVA_HOME=/usr/lib/jvm/java-18-openjdk-amd64
        echo "$ echo $JAVA_HOME"
        echo $JAVA_HOME
        export PATH=$PATH:$JAVA_HOME/bin
        echo "$ echo $PATH"
        echo $PATH

        update-alternatives --display java
        echo "$ java -version"
        java -version
        echo "$ javac -version"
        javac -version

        sudo apt-get install -y maven
        echo "$ mvn -v"
        mvn -v

    - name: build
      run: |
        mvn compile test-compile
    
    - name: test
      run: |
        mvn test
